'https://github.com/tmrcs/images/blob/master/UML/dbUtils.png
's
@startuml
class DButils {
  -con : Connection
  +DButils(String)
  +connect() : void
  +executeQuery(String) : ResultSet
  +executeQuery(PreparedStatement) : ResultSet
  +executeUpdate(String) : int
  +executeUpdate(PreparedStatement) : int
  +getConnection() : Connection
  +close() : void
}

class DBUserData {
  -user : String
  -passwd : String
  -server : String
  -dbname : String
  -propFilePath : String
  -baseDirectory : String
  -propFileName : String
  +DBUserData(String)
  +getProperties() : Properties
  +checkPropContents(Properties) : void
  +createNew PropertiesFile() : void
  +getDB_User() : String
  +getDB_Passwd() : String
  +getDB_Server() : String
  +getDB_DBName() : String
}

class DbUserHandler {
  -insert : String
  +DbUserHandler(DButils)
  +add(Entity) : int
  +getAll() : ArrayList<Entity>
  +get(String, String) : ArrayList<Entity>
  +getByEmail(String) : ArrayList<Entity>
  +getByUsername(String) : ArrayList<Entity>
  +update() : int
  +remove(String) : boolean
  +toInsertString(User) : String
}

class DbCategoryHandler {
  -insert : String
  +DbCategoryHandler(DButils)
  +add(Entity) : int
  +getAll() : ArrayList<Entity>
  +get(int) : ArrayList<Category>
  +update() : int
  +remove(String) : boolean
}

class DbPromotionHandler {
  -insert : String
  +DbPromotionHandler(DButils, UserHandler, CategoryHandler)
  +add(Entity) : int
  +getAll() : ArrayList<Entity>
  +get(String, String) : ArrayList<Entity>
  +updateSale(String) : boolean
  +remove(String) : boolean
  +getbyOwner(String) : ArrayList<Entity>
  +getbyCategory(String) : ArrayList<Entity>
  +getbyLocation(String) : ArrayList<Entity>
  +getbyID(String) : ArrayList<Entity>
  +getbyDate(String) : ArrayList<Entity>
  +getbyDate(int, int) : ArrayList<Entity>
  +getbyAvailability(String) : ArrayList<Entity>
  +getListOfResults(ResultSet) : ArrayList<Entity>
  +toInsertString(Promotion) : String
  +getAllLocations() : ArrayList<String>
  +update() : int
}

class DbPurchaseHandler {
  -insert : String
  +DbPurchas eHandler(DButils, PromotionHandler)
  +add(Entity) : int
  +getAll() : ArrayList<Entity>
  +getbyID(String) : ArrayList<Entity>
  +getbyOwner(String) : ArrayList<Entity>
  +getbyPromotion(String) : ArrayList<Entity>
  +getColumn(String, String) : ArrayList<Entity>
  +update() : int
  +remove(String) : boolean
  +toInsertString(Purchase) : String
}

DButils "0..1" --> "0..1" DBUserData : -userData
DbUserHandler "0..1" --> "0..1" DButils : -dbutils
DbCategoryHandler "0..1" --> "0..1" DButils : -dbutils
DbPromotionHandler "0..1" --> "0..1" DButils : -dbutils
DbPurchaseHandler "0..1" --> "0..1" DButils : -dbutils

@enduml