'https://github.com/tmrcs/images/blob/master/UML/PathTree.png
's
@startuml
class PathTree<T> {
  -SeparatorChar : String
  +PathTree()
  +add(T) : void
  +searchChildren(TNode<T>, String) : TNode<T>
  +getDefaultVal(String)
  +setDefaultPath(String, T) : void
  +addChild(TNode<T>, String) : TNode<T>
  +get(String, HashMap<String, String>) : TNode<T>
  +searchPlaceholders(TNode<T>, int, String[], HashMap<String, String>) : TNode<T>
  +isPlaceHolder(String) : boolean
  +extractKeyFromPlaceHolder(String) : String
  +getAllTemplates() : ArrayList<String>
  +insertAllTemplates(TNode<T>, ArrayList<String>) : ArrayList<String>
}

class TNode<E> {
  -path : String
  -value : E
  +TNode(String)
  +TNode(String, E)
  +TNode()
  +getPath() : String
  +getValue() : E
  +getChild() : TNode<E>
  +getNext() : TNode<E>
  +setValue(E) : void
  +setNext(TNode<E>) : void
  +setChild(TNode<E>) : void
}

class Parser<T> {
  +Parser()
  +getTree() : PathTree<T>
}

class FormatParser {
  +FormatParser(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +addFormatters(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler) : void
  +get(String, String) : Formatter
}

class CommandParser {
  +CommandParser(CommandExecutor, FormatParser, UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +CommandParser()
  +addCommands(CommandExecutor, FormatParser, UserHandler, PromotionHandler, PurchaseHandler) : void
  +get(String, HashMap<String, String>) : Command
}

Parser " " --> "0..1" PathTree : #tree
TNode " " --> "0..1" TNode : -next
TNode " " --> "0..1" TNode : -child
PathTree " " --> "0..1" TNode : -defaultNode
PathTree " " --> "0..1" TNode: +head
Parser <|-- FormatParser
Parser <|-- CommandParser

@enduml