'https://github.com/tmrcs/images/blob/master/UML/Formatters/TextFormatters.png
's
@startuml
class TextFormatter {
  -template : String
  +TextFormatter(String)
  +formatAll(ArrayList<String>, ArrayList<Entity>) : void
}

class TextUserFormatter {
  +TextUserFormatter()
  +formatOne(ArrayList<Entity>) : ArrayList<String>
  +formatAll(ArrayList<Entity>) : ArrayList<String>
}

class TextPromotionFormatter {
  +TextPromotionFormatter()
  +formatOne(ArrayList<Entity>) : ArrayList<String>
  +formatAll(ArrayList<Entity>) : ArrayList<String>
  +formatLocation(ArrayList<Entity>, String) : ArrayList<String>
  +formatCategory(ArrayList<Entity>, String) : ArrayList<String>
  +formatStatus(ArrayList<Entity>, String) : ArrayList<String>
}

class TextPurchaseFormatter {
  +TextPurchas eFormatter()
  +formatOne(ArrayList<Entity>) : ArrayList<String>
  +formatAll(ArrayList<Entity>) : ArrayList<String>
}

TextFormatter <|-- TextUserFormatter
TextFormatter <|-- TextPromotionFormatter
TextFormatter <|-- TextPurchaseFormatter

@enduml