'https://github.com/alihitawala/DesignPatterns/blob/master/src/main/java/com/learning/patterns/behavioral/interpreter/UML-Interpreter.png
'o
@startuml
class BooleanExp {
}

class AndExp {
}

class OrExp {
}

class VariableExp {
}

class NotExp {
}

class ConstantExp {
}

class Context {
}

class Runner {
}

BooleanExp <|-- AndExp
BooleanExp <|-- OrExp
BooleanExp <|-- VariableExp
BooleanExp <|-- NotExp
BooleanExp <|-- ConstantExp

AndExp "1" --> "1" BooleanExp
OrExp "1" --> "1" BooleanExp
NotExp "1" --> "1" BooleanExp

Runner ..> AndExp : <<create>>
Runner ..> OrExp : <<create>>
Runner ..> VariableExp : <<create>>
Runner ..> NotExp : <<create>>
Runner ..> ConstantExp : <<create>>
Runner ..> Context : <<create>>

@enduml