'https://github.com/alihitawala/DesignPatterns/blob/master/src/main/java/com/learning/patterns/structural/bridge/UML-Bridge.jpg
'o
@startuml
class StackImpl {
}

class StackList {
}

class StackArray {
}

class Stack {
}

class StackFIFO {
}

class StackHanoi {
}

StackImpl <|-- StackList
StackImpl <|-- StackArray
Stack <|-- StackFIFO
Stack <|-- StackHanoi
Stack ..> StackList : " "
Stack ..> StackArray : " "
StackFIFO ..> StackList : " "

StackFIFO " " --> " " StackImpl
Stack " " --> " " StackImpl

@enduml