'https://github.com/GisTekJNKS/Test/blob/master/TestJob/src/com/company/diagram.png
@startuml
interface ITransportationOfPeople {
  + drive() void
  + park() void
  + reverse() void
  + numberOfPassengers int
}

interface ICargoTransportation {
  + drive() void
  + park() void
  + reverse() void
  + cargoWeight int
}

class Automobile {
  + company String
  + model String
  + drive() void
  + park() void
  + reverse() void
}

class Van {
  + maxCargoWeight int
  + maxCountOfPassenger int
  + Van(String, String)
  + drive() void
  + transportCargo() void
  + transportPeoples() void
  + checkLoadedValue(int) void
  + checkPassengersCount(int) void
  + cargoWeight int
  + numberOfPassengers int
}

class Truck {
  + maxCargoWeight int
  + Truck(String, String)
  + drive() void
  + transportCargo() void
  + checkLoadedValue(int) void
  + cargoWeight int
}

class SportCar {
  + drive() void
}

class Main {
  + main(String[]) void
}

Van --|> Automobile
Truck --|> Automobile
SportCar --|> Automobile
Van ..|> ITransportationOfPeople
Van ..|> ICargoTransportation
Truck ..|> ICargoTransportation
@enduml
