'https://github.com/marcelocure/agile-estimates/blob/master/presentation_images/class_diagram.png.png
@startuml
class Profile {
  - id
  - name
}

class User {
  - id
  - name
  - username
  - password
  - profile
}

class Session {
  - id
  - username
  - login_date
}

class SessionManager {
  - getSession()
  - createSession()
  - removeSession()
  - is_there_a_valid_session()
}

class CryptUtils {
  - key
  - encrypt()
  - decrypt()
}

class Project {
  - id
  - name
  - trello_board
  - users
  - sprints
}

class Sprint {
  - id
  - id_project
  - start_date
  - end_date
  - points_estimated
  - points_delivered
  - number_of_tests
  - date_scanned
  - id_user
}

class Customer {
  - id
  - name
  - country
  - operationArea
  - project
}

User "1" .. "1" Profile
Session "*" .. "1" User
SessionManager .. Session : utiliza
User .. CryptUtils : criptografa
Project "1" .. "*" Sprint
Project "*" .. "*" User
Customer "1" .. "*" Project
@enduml
