'https://github.com/peperbol/Project_Pablo_Lost_Kitten/blob/master/klassendiagram.jpg
'o
@startuml
' Color legend:
' Blue (Pepijn Willekens)
' Green (Phedra Moerloos)
' Red (Thessa Moerloos)

class ObjectInScene <<Abstract Class>> {
  ' Fields
  - coordinate
  - gameObject
  ' Properties
  - Coordinate
  ' Methods
  + ObjectInScene
}

class Block <<Class>> {
  ' Fields
  - color
  - entities
  ' Properties
  - Color
  - Entities
  ' Methods
  + AddEntity
  + Block
  + IsEntityInList
  + RemoveEntity
}

class Entity <<Abstract Class>> {
  ' Fields
  - grid
  - typeOfEntity
  ' Properties
  - Grid
  - Height
  - Position
  - TypeOfEntity
  - Width
  ' Methods
  + CollideEnter
  + CollideLeave
  + Entity
}

class Activatable <<Abstract Class>> {
  ' Methods
  + Activatable
  + Activate
}

class Lever <<Class>> {
  ' Fields
  - area
  - IsActivated
  ' Properties
  - Height
  - Width
  ' Methods
  + Activate
  + IsInArea
  + Lever
  + ScanForAdjace...
}

class Teleporter <<Class>> {
  ' Fields
  - destination
  ' Properties
  - Height
  - Width
  ' Methods
  + Activate
  + Teleporter
}

class Player <<Class>> {
  ' Fields
  - currentColorBlo...
  - perspective
  ' Properties
  - CurrentColorBl...
  - Height
  - Perspective
  - Width
  ' Methods
  + CheckForActiva...
  + Move
  + Player
}

class Exit <<Class>> {
  ' Properties
  - Height
  - Width
  ' Methods
  + CollideEnter
  + Exit
}

class Level <<Class>> {
  ' Fields
  - entities
  - grid
  - template
  - worldRoot
  ' Properties
  - Grid
  - Height
  - Template
  - Width
  ' Methods
  + BuildLevel
  + GetPartOfGrid
  + Level
  + SetCameraPosit...
}

class Coordinates <<Class>> {
  ' Fields
  - XPosition
  - XSCALE
  - YPosition
  - YSCALE
  - ZVALUE
  ' Properties
  - Copy
  - XPosition
  - YPosition
  ' Methods
  + Coordinates (+...)
  + GetUnityPosition
}

ObjectInScene <|-- Block
ObjectInScene <|-- Entity
Entity <|-- Activatable
Entity <|-- Player
Entity <|-- Exit
Activatable <|-- Lever
Activatable <|-- Teleporter

note "BlockField" as N1
Entity -- N1

@enduml
