'https://github.com/athompson0/as1/blob/master/doc/UML%20Diagram.png
@startuml
class LogEntryList {
  -ArrayList<LogEntry> logs
  -float total
  +void setLogs(ArrayList<LogEntry> logs)
  +LogEntry getLog(int index)
  +void add(LogEntry log)
  +void replace(LogEntry oldLog, LogEntry newLog)
}

class LogEntry {
  -Date date
  -String station
  -Float odometer
  -String grade
  -Float amount
  -Float ucost
  -Float total
  +LogEntry(Date date, String station, Float odometer, String grade, Float amount, Float ucost)
  +String toString()
}

class IncompleteEntry {
  -Date date
  -String station
  -Float odometer
  -String grade
  -Float amount
  -Float ucost
  +IncompleteEntry()
  +IncompleteEntry(LogEntry log)
  +boolean isComplete()
  +LogEntry createLogEntry()
}

class ListActivity {
  -ListView logList
  -LogEntryList logs
  -ArrayAdapter<LogEntry> adapter
  -TextView totalText
  +void onCreate()
  +void onClick(...) 
  +void onClick(...) 
  +void updateText()
  +void onActivityResult()
  +void onStart()
  +void loadFromFile()
  +void saveInFile()
}

class EditActivity {
  -void onCreate()
  -void onClick(...) 
  -void onClick(...) 
  -boolean validEntries(IncompleteEntry entries)
}

class NewLogActivity {
  -void onCreate()
  -void onClick(...) 
  -void onClick(...) 
  -IncompleteEntry parseEntries()
}

LogEntryList "1" o-- "0..*" LogEntry
ListActivity "1" *-- "1" LogEntryList
ListActivity  -- EditActivity : LA calls EA
ListActivity  --  NewLogActivity : LA calls NLA
NewLogActivity "1" *-- "1" IncompleteEntry : NLA temporary creates an IE object 
IncompleteEntry  --  LogEntry : IE can access data from, and write data to LE
LogEntry "1" --o "1" NewLogActivity: NLA creates an LE object to pass to LA
EditActivity "1" o-- "1" LogEntry : EA has one LE object that it alters
@enduml
