' https://github.com/kukuruza/cmu-bus/blob/master/server/classDiagrams/servlets.png
' s
@startuml
class GetDatabaseServlet <<bustracker.server.servlets>> {
  + GetDatabaseServlet()
  + doGet()
}

class DatabaseConnector <<bustracker.server.dbhelpers>> {
  + DatabaseConnector()
  + getDbPath()
  + getSchedule()
  + getAllStops()
  + getStopsByStreet()
  + getBusesForStop()
  + closeConnection()
}

class DbStructure <<bustracker.server.dbhelpers>> {
  + DbStructure()
  + allStopsRequestString()
  + stopsByStreetRequestString()
  + busesRequestString()
  + scheduleRequestString()
  + scheduleRequestString()
}

class QueryServlet <<bustracker.server.servlets>> {
  + _parameterMap: Map<String,String[]>
  + _stopName: String
  + _busNames: ArrayList<String>
  + _busDirs: ArrayList<String>
  + QueryServlet()
  + doGet()
}

class DbTime <<bustracker.server.dbhelpers>> {
  + DeepNight: int
  + _calendar: Calendar
  + DbTime()
  + setTime()
  + getMinutesTotal()
  + toString()
  + getCurrentDbTime()
  + getWeekDay()
}

GetDatabaseServlet ..> DatabaseConnector
DatabaseConnector ..> DbStructure
DatabaseConnector ..> DbTime
DbTime ..> DbStructure
@enduml