' https://github.com/kukuruza/cmu-bus/blob/master/client/classDiagrams/routeQuery.png
' s
@startuml
class GlobalManager <<cmu18641.bustracker.ws>> {
  + timeQueryManager: TimeQueryManager
  + locationService: LocationService
  + GlobalManager()
  + getBusesByStop()
  + getStopsByCurrentLocation()
  + getStopByAddress()
  + killLocationService()
  + getSchedule()
  + updateDatabase()
}

class RouteQueryManager <<cmu18641.bustracker.ws>> {
  + RouteQueryManager()
  + getBusesByStop()
  + getStopsByCurrentLocation()
  + getAllStops()
  + getStopByAddress()
}

class RouteQueryInterface <<cmu18641.bustracker.ws>> {
  + getBusesByStop()
  + getStopsByCurrentLocation()
  + getStopByAddress()
  + getAllStops()
}

GlobalManager --> "0..1" RouteQueryManager : ~routeQueryManager
RouteQueryManager ..|> RouteQueryInterface
@enduml