'https://github.com/sebastianruder/BART/blob/master/BART/documents/uml2.png
' o
@startuml
package "pkg" {

    class Mention {
      + moreRepresentativeThan(m : Mention) : boolean
    }
  

  
    interface CorefResolver {}
  


    abstract class Sieve {
      - mentions : ArrayList<Mention>
      + compareEntitites(mentionEntity : Entity, potentialAntecedent : Entity) : boolean
      + runSieve(m : Mention) : void
    }

    class StringMatchSieve {
      + compareEntitites(mentionEntity : Entity, potentialAntecedent : Entity) : boolean
      + runSieve(m : Mention) : void
    }

    class SpeakerIdentificationSieve
  }

  class Entity {
    - id : Integer
    - types : Set
    - attributes : Set
    - relations : Set
    - corefChain : ArrayList
    - isFirstMention : boolean
    - isProperName : boolean
    - isRepresentativeMention : boolean
    + merge(m : Mention) : void
    + addMention(m : Mention) : void
  }

  class SieveDecoder {
    + decodeDocument(mentions : List<Mention>, antecedents : Map<Mention,Mention>) : DisjointSet<Mention>
  }


' Relationships
Mention "1" *-- "0..*" Entity

CorefResolver <|.. SieveDecoder

Sieve <|-- StringMatchSieve
Sieve <|-- SpeakerIdentificationSieve

SieveDecoder --> Sieve
SieveDecoder --> Mention

@enduml