' https://github.com/sriram-mahavadi/extlp/blob/master/doc/images/btree_uml.png
' o
@startuml
class IteratorMap {
    + register(i : Iterator)
    + unregister(i : Iterator)
    + find(b : BID, pos : int) : Iterator
}

class BTree {
    - height : int
    + insert(v : Value) : Iterator
    + erase(k : Key) : int
    + find(k : Key) : Iterator
    + lower_bound(k : Key) : Iterator
}

class RootNode {
    + insert(k : Key, b : BID)
    + erase(k : Key)
    + find(k : Key) : BID
}

class Splitter {
    - k : Key
    - b : BID
}

class LeafCache {
    + getLeaf(b : BID) : Leaf
    + prefetch(b : BID)
    + getNewLeaf(out b : BID) : Leaf
    + deleteLeaf(b : BID)
}

class NodeCache {
    - nodes : Array
    - BID2int : Map
    - pager : Pager
    - freeNodes : List
    + getNode(b : BID) : Node
    + getNewNode(out b : BID) : Leaf
    + deleteLeaf(b : BID)
    + fixNode(b : BID)
    + unfixNode(b : BID)
}

class Leaf {
    - me : BID
    - pred : BID
    - succ : BID
    - size : int
    + find(k : Key) : Iterator
    + increment(inout i : Iterator)
    + decrement(inout i : Iterator)
    + lower_bound(k : Key) : Iterator
    + insert(v : Value, out s : Splitter) : Iterator
    + erase(k : Key)
}

class Iterator {
    + Iterator()
    # Iterator(im : IteratorMap, b : BID, o : int)
}

class Node {
    - me : BID
    - size : int
    + find(k : Key, h : int) : Iterator
    + lower_bound(k : Key, h : int) : Iterator
    + insert(v : Value, h : int, out s : Splitter) : Iterator
    + erase(k : Key, h : int)
}

' Relationships
BTree *-- RootNode
BTree *-- LeafCache
BTree  *-- IteratorMap
BTree *-- NodeCache
BTree --> Node

Node --> Node
Node --> Leaf
Node --> NodeCache
Node --> LeafCache

Iterator --> Leaf
Iterator --> LeafCache
Iterator -- IteratorMap

Leaf --> LeafCache
Leaf -- BTree
Leaf --> IteratorMap


@enduml
