' https://github.com/criusmq/woodstock/blob/master/docs/basicuml.svg
' o
@startuml

' Define Legend (not rendered in PlantUML, but for reference)
' composition: O-- 
' dependency: ..>
' realization: ..|>
' association: --

' Classes and Interfaces
class Graph <<interface>>
class PetriNet <<interface>>
class SimplePetriNet
class PetriNetImporter
class Mutation <<interface>>
class App
class WebApp
class GraphRenderer
class WebSocketServer
class WebSocketClient
class MichaelisMenten
class PINvariant
class MotifDetection

' Relationships
' Composition
Graph  o--  PetriNet
PetriNet  o--  App
PetriNet  o--  WebApp
App  o--  WebSocketServer
WebApp  o--  GraphRenderer
WebApp  o--  WebSocketClient

' Dependency
SimplePetriNet ..> PetriNet
MichaelisMenten ..> Mutation
PINvariant ..> Mutation
MotifDetection ..> Mutation

' Realization
Mutation <|.. App

' Association
WebSocketClient --> WebSocketServer : Communication channel

@enduml