@startuml
skinparam rectangle {
    BackgroundColor<<abstract>> LightYellow
    BackgroundColor<<create>> LightYellow
}

class Visitor {
    <<abstract>>
}

class User {
    +firstname: String
    +lastname: String
    +username: String
    +password: String
    +mobilephoneNumber: String
    +gender: Character
    +picturePath: String
    +currentZone: TaxiZone
    +currentLocation: Location
    +codiceFiscale: String
}

class Admin {
    +username: String
    +password: String
}

class Guest {
}

class TaxiDriver {
    +licenseNumber: String
    +availability: char
    +isEmergency: char
    +carModel: String
    +carId: CarNumber
}

class Scheduler {
    +zones: TaxiZone
}

class TaxiZone {
    +carIdQueue: CarNumber*
    +emergencyQueue: CarNumber*
    +requestQueue: Request*
    +zoneId: String
    +centerPoint: Location
}

class CarNumber {
    +id: String
}

class Location {
    +coordinates: String
    +streetName: String
    +number: integer
}

class DriveCommunicationMessage {
    +sender: User
    +receiver: User
    +timeStamp: DateTime
    +startpoint: Location
    +endpoint: Location
}

class DateTime {
    +timeStamp: Time
    +dateStamp: Date
}

class Date {
    +year: integer
    +month: integer
    +day: integer
}

class Time {
    +hours: integer
    +minutes: integer
}

class Request {
    +maximumWaitingTime: Time
}

class Response {
    +accepted: char
    +estimatedTimeWaiting: Time
    +estimatedPrice: integer
}

class Drive {
    +driveId: String
    +reports: Report*
    +userRequest: Request
    +taxiResponse: Response
}

class Report {
    +reason: String
    +id: String
}

' Inheritance
Visitor <|-- Admin
Visitor <|-- Guest
User <|-- TaxiDriver
Visitor <|-- User

' Associations
Scheduler "1" *--> "1..*" TaxiZone
Scheduler *--  Request
Scheduler ..>  Drive
TaxiZone "1" *--  Location
TaxiZone  o-- "0..*" CarNumber
TaxiZone  *--> "1*" User
User  *--> "1" Location
User "1" -- "0..*" DriveCommunicationMessage
DriveCommunicationMessage  *--> "1" DateTime
DateTime  *--> "1" Date
DateTime  *--> "1" Time
DriveCommunicationMessage "1" <|-- "0..*" Response
DriveCommunicationMessage  <|--  Request
TaxiDriver "1" *-- "1" CarNumber
TaxiDriver "1" -- "0..*" Report
TaxiDriver "1" --  DriveCommunicationMessage
TaxiDriver  ..>  Response
User "1" -- "0..*" Report
Report "1" --|>  DriveCommunicationMessage
DriveCommunicationMessage "0..*" *--> "2" Location

Drive "1" o-- "0..*" Report


Request *--> "0..1" Time
Response  *--> "1" Time

' Create dependencies
User ..> "0..*" Drive : <<create>>
User ..> Request : <<create>>

@enduml