@startuml
package "main" {
  class MainScreenController {
    -resources: ResourceBundle
    -location: URL
    -MainscreenButton: Button
    -playerFish: PlayerFish
    -entities: ArrayList<EnemyFish>
    -screenbox: BoundingBox
    -frames: int
    -MULTIPLIER: double = 1.05
    -scoreText: Text = newText()
    -currScore: int
    -input: ArrayList<String>
    -background: Image = new Image("Fishy_bg.jpg")
    +PlayEvent(event: MouseEvent): void
    +MenuEvent(event: MouseEvent): void
    +QuitEvent(event: MouseEvent): void
    +init(): void
    +initialize(): void
    -setScreenbox(boundingBox: BoundingBox): void
    +getScreenbox(): BoundingBox
    -playerHasWon(): boolean
    -renderStatics(gc: GraphicsContext): void
    -renderNonStatics(gc: GraphicsContext): void
    -handlePlayerMovement(i: int): void
    -generateEnemyFish(): void
  }

  class Game {
    +stage: Stage
    +pane: Pane
    -resX: int = 1280
    -resY: int = 720
    +main(args: String[]): void
    +start(firstStage: Stage): void
    +switchScreen(bestand: String): void
    +getResY(): int
    +getResX(): int
    +setResX(resX: int): void
    +setResY(resY: int): void
  }

  class PlayerFish {
    -leftImageName: String = "Fish_Right_Transparent.png"
    -rightImageName: String = "Fish_Right_Transparent.png"
    -leftImage: Image
    -rightImage: Image
    -isAlive: boolean
    -score: int
    +PlayerFish(movespeed: int, isAlive: boolean, leftImgFileName: String, rightImgFileName: String, sprite: Sprite, score: int)
    +createPlayerFish(): PlayerFish
    +grow(multiplier: double): void
    +playerDies(enemyfish: EnemyFish): boolean
    +isAlive(): boolean
    +setAlive(isAlive: boolean): void
  }

  class EnemyFish {
    -leftImageFileName: String = "EnemyFish_Left.png"
    -rightImageFileName: String = "EnemyFish_Right.png"
    -isLefty: boolean
    +EnemyFish(movespeed: int, isLefty: boolean, sprite: Sprite)
    +generateFish(): EnemyFish
    +isLefty(): boolean
    +setLefty(isLefty: boolean): void
  }

  class Entity {
    -moveSpeed: int
    -sprite: int
    +Entity(moveSpeed: int, sprite: Sprite)
    +intersects(other: Entity): boolean
    +intersectsLeftScreenEdge(): boolean
    +intersectsRightScreenEdge(): boolean
    +intersectsUpperScreenEdge(): boolean
    +intersectsUnderScreenEdge(): boolean
    +getSprite(): Sprite
    +setSprite(sprite: Sprite): void
    +getMoveSpeed(): int
    +setMoveSpeed(moveSpeed: int): void
  }

  class OptionsController {
    -resources: ResourceBundle
    -location: URL
    -OnButton: Button
    -OffButton: Button
    -BackButton: Button
    +BackButtonEvent(event: MouseEvent): void
    +MusicOnEvent(event: MouseEvent): void
    +MusicOffEvent(event: MouseEvent): void
    +initialize(): void
  }

  class LosingScreenController {
    -resources: ResourceBundle
    -location: URL
    -MainscreenButton: Button
    +MainScreenEvent(event: MouseEvent): void
    +initialize(): void
  }

  class WinningScreenController {
    -resources: ResourceBundle
    -location: URL
    -MainscreenButton: Button
    +MainScreenEvent(event: MouseEvent): void
    +initialize(): void
  }

  class BoundingBox {
    -x: int
    -y: int
    -height: int
    -width: int
    +BoundingBox(x: int, y: int, width: int, height: int)
    +intersects(other BoundingBox): boolean
    +getY(): int
    +setY(y: int): void
    +getX(): int
    +setX(X: int): void
    +getWidth(): int
    +setWidth(y: int): void
  }

  class Sprite {
    -img: Image
    -boundingBox: BoundingBox
    +Sprite(img: Image, boundingBox: BoundingBox)
    +updateX(x: int): void
    +updateY(y: int): void
    +render(gc: GraphicsContext): void
    +intersects(s: Sprite): boolean
    +getImage(): Image
    +setImage(img: Image): void
    +getBoundingBox(): BoundingBox
    +setBoundingBox(boundingBox: BoundingBox): void
    +equals(other: Object): boolean
  }
}

MainScreenController "1" <--> "1" Game : has
Game "1" <--> "1" PlayerFish : has
Game "1" <--> "*" EnemyFish : has
Game "1" <--> "1" WinningScreenController : has
Game "1" <--> "1" LosingScreenController : has
Game "1" <--> "1" OptionsController : has
PlayerFish --|> Entity
EnemyFish --|> Entity
BoundingBox "1" <--> "1" Sprite : has

Sprite "1" <--> "1" Entity : modeled by

@enduml