@startuml
'https://github.com/sshy3/mmc/blob/master/CS5590vc_lab1/class(uml).jpg
'o
class "Motion Sensor" {
  Sensor id
  Sensor Value
  Sendidvalue()
}

class "Controller" {
  ownernumber
  Display()
  Activatealarm()
  Receiveidvalue()
  TurnOnlights()
  Callowner()
  Setownernum()
}

class "Entry Sensor" {
  Sensor Value
  Sensor Id
  Sendidvalue()
}

class "Smoke Sensor" {
  Sensor Id
  Sensor Value
  Sendidvalue()
}

"Motion Sensor" -- "Controller"
"Controller" -- "Entry Sensor"
"Controller" -- "Smoke Sensor"
@enduml