@startuml
'https://github.com/kiith-sa/SoftwareEngineering/blob/master/ClassDiagram.png
'o
class "Registered User" {
  -ID
  -Name
}

class "AssetOwner" {
  -assetTypes
}

class "Asset" {
  -ID
  -URI
  -owner
  -isCompleted
  -isReviewed
  +complete()
  +updateURI()
  +review()
}

class "3DAsset" {
  -vertices
  -vertexFormat
  -textures
  -fileFormat
}

class "ImageAsset" {
  -width
  -height
  -pixelFormat
  -fileFormat
}

class "SoundAsset" {
  -length
  -frequency
  -bitDepth
  -fileFormat
}

class "TextAsset" {
  -translations
  -encoding
}

class "AssetSystem" {
  +createAsset()
  +uploadAsset()
  +deleteAsset()
  +updateAsset()
}

class "AssetSystemFrontend" {
  +mainDialog()
  +uploadDialog()
}

class "AssetStorage" {
  -assets
  -storageBackends
  +addAsset()
  +removeAsset()
  +updateAsset()
}

class "AssetStorageBackend" {
  -files
  -pendingChanges
  +updateFile()
  +removeFile()
  +unlock()
  +lock()
}

class "GitAssetStorageBackend" {
  -repoURL
  -branch
  +commit()
  +push()
  +stage()
}

"Registered User" <|-- "AssetOwner"
"Registered User" -...-> "AssetSystemFrontend": << use >>

"Asset" o-- "AssetOwner"

"AssetSystem" <-...- "AssetSystemFrontend": << access >> communicates
"Asset" <-...- "AssetSystem": << instantiate >>


"Asset" <|-- "3DAsset"
"Asset" <|-- "ImageAsset"
"Asset" <|-- "SoundAsset"
"Asset" <|-- "TextAsset"

"AssetStorage" *-- "Asset" : n:0
"AssetStorage" --* "AssetSystem"
"AssetStorageBackend" --* "AssetStorage" : n:1


"AssetStorageBackend" <|-- "GitAssetStorageBackend"

@enduml