'https://github.com/khasang/JQuiz/blob/develop/data/architecture/uml/class_diagram2.jpg
'o
@startuml
' Classes
class Model {
  +getListQuestion(int) List<Question>
}

class ModelImpl {
  -question Question
  +getListQuestion(int) List<Question>
}

class Question {
  -discription String
  -question String
  -completed boolean
  -difficult String
  -answer4 String
  -chosen boolean
  -answer1 String
  -theme String
  -answer2 String
  -answer3 String
}

class PresenterImpl {
  -test BaseTest
  -model Model
  +PresenterImpl()
  +onClickFAB() void
  +getTest(TypeTest) BaseTest
}

class Presenter {
  +onClickFAB() void
  +getTest(TypeTest) BaseTest
}

class MainActivity {
  -presenter Presenter
  +onCreate(Bundle) void
  +onCreateOptionsMenu(Menu) boolean
  +onOptionsItemSelected(MenuItem) void
  +onClickFAB() void
}

class BaseTest {
}

class QuickTest {
}

class TypeTest {
}

class DbAdapter {
  -DB_NAME String
  -TABLE_NAME String
  -DB_VERSION int
  -dbHelper DbHelper
  -context Context
  -database SQLiteDatabase
}

class DbHelper {
  +DbHelper(Context, CursorFactory)
  +onCreate(SQLiteDatabase) void
  +onUpgrade(SQLiteDatabase, int, int) void
}

' Relationships
Model <|-- ModelImpl
Presenter <|-- PresenterImpl
BaseTest <|-- QuickTest

ModelImpl "1" --> "1" Question
PresenterImpl "1" --> "1" Model
PresenterImpl "1" --> "1" BaseTest
MainActivity "1" --> "1" Presenter
DbAdapter "1" --> "1" DbHelper

PresenterImpl ..> ModelImpl : <<create>>
PresenterImpl ..> Presenter : <<create>>
MainActivity ..> PresenterImpl : <<create>>

@enduml