'https://github.com/huesitos/rim/blob/master/doc/Class%20Diagram.png
'o
@startuml
package "pkg" {
  class TestCase {
    +identifier : String
    +title : String
    +steps : String
    +preconditions : String
    +postconditions : String
  }

  class Requirement {
    +title : String
    +description : String
    +type : String
    +identifier : String
    +priority : int
  }

  class UseCase {
    +title : String
    +preconditions : String
    +steps : String
    +postconditions : String
    +requirements : ArrayList
    +priority : int
    +identifier : String
  }

  class Project {
    +name : String
    +description : String
    +scope : String
  }

  class Summary {
    +passed : int
    +failed : int
    +skiped : int
    +total : int
  }

  class TestRun {
    +date : Date
    +test_case_report : ArrayList
  }

  class Issue {
    +title : String
    +label : String
    +status : int
    +comments : String
  }

  class Report {
    +test_case : ObjectId
    +result : String
    +comments : String
  }

  TestCase "0..*" --> "1..*" Requirement
  TestCase "0..*" --> "0..*" UseCase
  UseCase "0..*" --> "1..*" Requirement
  Project "0..*" --> "1" Requirement
  Project "1" --> "0..*" TestCase : + requirements
  Project "1" --> "0..*" UseCase : + use_cases
  Project "1" --> "0..*" Issue : + issues
  Project "1" --> "0..*" TestRun
  TestRun "1" --> "1" Summary : + summary
  TestRun "1" --> "1..*" Report : - reports
  Report "1" --> "1..*" Issue : + issue
}

@enduml