'https://github.com/tmrcs/images/blob/master/UML/HtmlElement.png
's
@startuml
interface HtmlElement {
  +WriteToList(ArrayList<String>) : void
}

class HtmlLinkText {
  -link : String
  +HtmlLinkText(String, String)
  +WriteToList(ArrayList<String>) : void
}

class HtmlTitle {
  -title : String
  +HtmlTitle(String)
  +WriteToList(ArrayList<String>) : void
}

class HtmlText {
  -text : String
  +HtmlText(String)
  +WriteToList(ArrayList<String>) : void
}

class HtmlFormElement {
  -inputType : String
  -argName : String
  -required : boolean
  +HtmlFormElement(String, String, boolean)
  +WriteToList(ArrayList<String>) : void
}

class HtmlLinkTag {
  +HtmlLinkTag(HtmlElement[])
  +HtmlLinkTag(HashMap<String, String>, String)
}

class HtmlTableRow {
  +HtmlTableRow(HtmlElement[])
}

class HtmlHeader {
  +HtmlHeader(HtmlElement[])
}

class HtmlListElement {
  +HtmlListElement(HtmlElement[])
}

class HtmlBody {
  +HtmlBody(HtmlElement[])
}

class HtmlContainer {
  -opener : String
  -closer : String
  +HtmlContainer(String, String, HtmlElement[])
  +HtmlContainer(String, String, HashMap<String, String>, HtmlElement[])
  +insert(HtmlElement) : boolean
  +WriteToList(ArrayList<String>) : void
}

class HtmlBreak {
  +HtmlBreak(HtmlElement[])
}

class HtmlPage {
  +HtmlPage(HtmlElement[])
}

class HtmlHeading {
  +HtmlHeading(int, HtmlElement[])
}

class HtmlForm {
  +HtmlForm(HashMap<String, String>, HtmlElement[])
}

class HtmlButton {
  +HtmlButton(HashMap<String, String>, String, HtmlElement[])
}

class HtmlTableData {
  +HtmlTableData(HtmlElement[])
}

class HtmlTableHeading {
  +HtmlTableHeading(HtmlElement[])
}

class HtmlList {
  +HtmlList(HtmlElement[])
}

class HtmlTable {
  +HtmlTable(int, int, HtmlElement[])
  +HtmlTable(HashMap<String, String>, HtmlElement[])
}

HtmlElement <|-- HtmlLinkText
HtmlElement <|-- HtmlTitle
HtmlElement <|-- HtmlText
HtmlElement <|-- HtmlFormElement
HtmlElement <|-- HtmlContainer


HtmlContainer " " --> "0..*" HtmlElement : +children
HtmlLinkTag --> HtmlContainer
HtmlTableRow --> HtmlContainer
HtmlHeader --> HtmlContainer
HtmlListElement --> HtmlContainer
HtmlBody --> HtmlContainer

HtmlBreak --> HtmlContainer
HtmlPage --> HtmlContainer
HtmlHeading --> HtmlContainer
HtmlForm --> HtmlContainer

HtmlButton --> HtmlContainer
HtmlTableData --> HtmlContainer
HtmlTableHeading --> HtmlContainer
HtmlList --> HtmlContainer
HtmlTable --> HtmlContainer

@enduml