'https://github.com/tmrcs/images/blob/master/UML/Handlers/DataHandler.png
's
@startuml
interface DataHandler {
  +add(Entity) : int
  +getAll() : ArrayList<Entity>
  +update() : int
  +remove(String) : boolean
}

class PurchaseHandler {
  +PurchaseHandler(PromotionHandler)
  +getbyID(String) : ArrayList<Entity>
  +getbyOwner(String) : ArrayList<Entity>
  +getbyPromotion(String) : ArrayList<Entity>
  +getPromoHandler() : PromotionHandler
  +getUs erHandler() : UserHandler
}

class PromotionHandler {
  +PromotionHandler(UserHandler, CategoryHandler)
  +get(String, String) : ArrayList<Entity>
  +getbyID(String) : ArrayList<Entity>
  +getbyOwner(String) : ArrayList<Entity>
  +getbyCategory(String) : ArrayList<Entity>
  +getbyLocation(String) : ArrayList<Entity>
  +getbyDate(String) : ArrayList<Entity>
  +getbyDate(int, int) : ArrayList<Entity>
  +getAllLocations() : ArrayList<String>
  +getByAvailability(String) : ArrayList<Entity>
  +updateSale(String) : boolean
  +getUs erHandler() : UserHandler
  +getCategoryHandler() : CategoryHandler
  +validate(HashMap<String, String>) : boolean
}

class UserHandler {
  +UserHandler()
  +get(String, String) : ArrayList<Entity>
  +getByEmail(String) : ArrayList<Entity>
  +getByUsername(String) : ArrayList<Entity>
  +update() : int
  +validate(HashMap<String, String>) : boolean
}

class CategoryHandler {
  +CategoryHandler()
  +get(int) : ArrayList<Category>
  +exists(int) : boolean
}

DataHandler <|-- PurchaseHandler
DataHandler <|-- PromotionHandler
DataHandler <|-- UserHandler
DataHandler <|-- CategoryHandler

PromotionHandler " " --> "0..1" UserHandler : -us erHandler
PromotionHandler " " --> "0..1" CategoryHandler : -categoryHandler
PurchaseHandler " " --> "0..1" PromotionHandler : -promoH

@enduml