'https://github.com/tmrcs/images/blob/master/UML/Formatters/HtmlFormatters.png
's
@startuml
class HTMLFormatter {
  -template : String
  +HTMLFormatter(String)
  +createHeader(String) : HtmlHeader
}

class HomeFormatter {
  +HomeFormatter()
  +format() : ArrayList<String>
}

class HTMLUserFormatter {
  -promoH : PromotionHandler
  -purchas eH : PurchaseHandler
  -width : int
  +HTMLUserFormatter(PromotionHandler, PurchaseHandler)
  +formatOne(ArrayList<Entity>) : ArrayList<String>
  +createListOfPurchases(String) : HtmlElement
  +createListOfPromotions(String) : HtmlElement
  +createTableOne(ArrayList<Entity>) : HtmlElement
  +createTableHeadings() : HtmlTable
  +formatAll(ArrayList<Entity>) : ArrayList<String>
  +createPostUs erForm() : HtmlElement
  +createTableAll(ArrayList<Entity>) : HtmlElement
}

class HTMLPromotionFormatter {
  -prefix : ArrayList<String>
  -width : int
  -catH : CategoryHandler
  -promoH : PromotionHandler
  -purchas eH : PurchaseHandler
  +HTMLPromotionFormatter(CategoryHandler, PromotionHandler, PurchaseHandler)
  +formatOne(ArrayList<Entity>) : ArrayList<String>
  +createListOfPurchases(Promotion) : HtmlList
  +createTableOne(ArrayList<Entity>) : HtmlElement
  +createTableHeadings() : HtmlTable
  +formatAll(ArrayList<Entity>) : ArrayList<String>
  +createLocationFilterList() : HtmlElement
  +createCategoryFilterList() : HtmlElement
  +createTable(ArrayList<Entity>) : HtmlElement
  +formatLocation(ArrayList<Entity>, String) : ArrayList<String>
  +formatCategory(ArrayList<Entity>, String) : ArrayList<String>
  +formatStatus(ArrayList<Entity>, String) : ArrayList<String>
  +createPostPromotionForm() : HtmlElement
}

class HTMLPurchaseFormatter {
  -width : int
  +HTMLPurchas eFormatter()
  +formatOne(ArrayList<Entity>) : ArrayList<String>
  +createTable(ArrayList<Entity>) : HtmlElement
  +formatAll(ArrayList<Entity>) : ArrayList<String>
}

HTMLFormatter <|-- HomeFormatter
HTMLFormatter <|-- HTMLUserFormatter
HTMLFormatter <|-- HTMLPromotionFormatter
HTMLFormatter <|-- HTMLPurchaseFormatter

@enduml