'https://github.com/tmrcs/images/blob/master/UML/TopLevelUML.png
's
@startuml
interface DataHandler {
  +add(Entity) : int
  +getAll() : ArrayList<Entity>
  +update() : int
  +remove(String) : boolean
}

class Command {
  -description : String
  +Command(FormatParser, DataHandler, String, String)
  +execute(HashMap<String, String>) : ArrayList<String>
  +toString() : String
  +shutdown() : boolean
  +getFormatter(String, String) : Formatter
}

class CommandLineUI {
  -kbd : Scanner
  +CommandLineUI()
  +run() : void
  +printData(ArrayList<String>, HashMap<String, String>) : void
  +executeDefaultCommand() : void
  +getInput() : String
  +toShutDown() : boolean
  +getCommandExecutor() : CommandExecutor
}

class CommandExecutor {
  +CommandExecutor(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +CommandExecutor(CommandParser, FormatParser)
  +executeCommand(String, HashMap<String, String>) : ArrayList<String>
  +getCommandParser() : CommandParser
  +getCurrentCommand() : Command
}

class FormatParser {
  +FormatParser(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +FormatParser(PathTree<Formatter>)
  +addFormatters(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler) : void
  +get(String, String) : Formatter
}

class CommandParser {
  +CommandParser(CommandExecutor, FormatParser, UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +CommandParser()
  +addCommands(CommandExecutor, FormatParser, UserHandler, PromotionHandler, PurchaseHandler) : void
  +get(String, HashMap<String, String>) : Command
}

class Listen {
  -server : Server
  +Listen(CommandExecutor)
  +execute(HashMap<String, String>) : ArrayList<String>
  +getCommandExecutor() : CommandExecutor
  +stopServer() : void
}

Command --> "0..1" DataHandler : #handler
CommandExecutor --> "0..1" Command : -currentCommand
CommandLineUI --> "0..1" CommandExecutor : -commandExecutor
CommandExecutor --> "0..1" FormatParser : -formatterParser
CommandExecutor --> "0..1" CommandParser : -commandParser
Listen -->"0..1" CommandExecutor : -executer
Command <|-- Listen
Command --> "0..1" FormatParser : #formatters

@enduml