'https://github.com/alihitawala/DesignPatterns/blob/master/src/main/java/com/learning/patterns/structural/composite/UML-Composite.png
'o
@startuml
class ComplexShape {
}

class Line {
}

class Rectangle {
}

class Shape {
}

ComplexShape "1" --> "*" Shape
Rectangle "1" --> "*" Shape
Line ..> Shape : <<create>>
Rectangle ..> Shape : <<create>>

Rectangle "1" --> "1" Shape
Rectangle ..> Line : <<create>>

@enduml