'https://github.com/albertoblaz/Wikious/blob/master/doc/v1-blogsystem/pictures/UML%20Business.png
'o
@startuml
class Blog {
  Blog
  Name
  User
  Entries[]
}

class Entry {
  Title
  Date
  Content
  Comments[]
  Likes
  Tags
  Comment
  Like
  Update
  AddObservers
}

class Comment {
  User
  Date
  Text
}

class User {
  Nick
  Email
  Age
  Location
}

Blog  o--  Entry
Entry  o--  Comment
Blog --> User
Comment --> User
@enduml
