'https://github.com/czervos/as1/blob/master/doc/as1UML.png
'o
@startuml
class StatsActivity {
  -counter: CounterModel
  -statsList: ArrayList<String>
  -statsCountsList: ArrayList<String>
  -customStatsAdapter: CustomStatsAdapter
  -monthList: ArrayList<LogModel>
  -daylist: ArrayList<LogModel>
  -hourList: ArrayList<LogModel>
  -weekList: ArrayList<LogModel>
  +onCreate(savedInstanceState: Bundle): void
  +setMonthStats(timeList: ArrayList<Calendar>): ArrayList<Calendar>
  +setDayStats(timeList: ArrayList<Calendar>): ArrayList<Calendar>
  +setHourStats(timeList: ArrayList<Calendar>): ArrayList<Calendar>
  +setWeekStats(timeList: ArrayList<Calendar>): ArrayList<Calendar>
}

class LogModel {
  -count: int
  -hourID: String
  -dayID: String
  -weekID: String
  -monthID: String
  +LogModel(calendar: Calendar): LogModel
  +getHour(): String
  +getDay(): String
  +getWeek(): String
  +getMonth(): String
  +getCount(): String
  +increment(): void
}

class CounterListModel {
  -counterList: ArrayList<CounterModel>
  +CounterListModel(): CounterListModel
  +getCounterList(): ArrayList<CounterModel>
  +setCounterList(counterList: ArrayList<CounterModel>): void
  +addCounter(counter: CounterModel): void
}

class CounterModel {
  -count: int
  -name: String
  -timeList: ArrayList<Calendar>
  +CounterModel(text: String): CounterModel
  +getCount(): Integer
  +getCounterName(): String
  +getTimeList(): ArrayList<Calendar>
  +increment(): void
  +setCounterName(text: String): void
  +zero(): void
}

class CounterListActivity {
  -counterList: CounterListModel
  -customAdapter: CustomAdapter
  +onResume(): void
  +onCreateContextMenu(menu: ContextMenu, view: View): void
  +onContextItemSelected(item: MenuItem): boolean
  +loadCounterList(): CounterListModel
  +onContextItemSelected(item: MenuItem): boolean
  +sort(array: ArrayList<CounterModel>): ArrayList<CounterModel>
}

class AddCounterActivity {
  +createCounter(view: View): void
}

class RenameCounterActivity {
  +renameCounter(view: View): void
}

class CustomAdapter {
  -counterListModel: CounterListModel
  -counters: ArrayList<CounterModel>
  +CustomAdapter(context: Context, cModel: CounterListModel): CustomAdapter
  +getView(position: int, convertView: View, parent: ViewGroup): View
}

class CustomStatsAdapter {
  -statsList: ArrayList<String>
  -statsCountsList: ArrayList<String>
  +CustomStatsAdapter(context: Context, sList: ArrayList<String>): CustomStatsAdapter
  +getView(position: int, convertView: View, parent: ViewGroup): View
}

class ViewHolder {
  -textView1: TextView
  -textView2: TextView
}

' Relationships
StatsActivity -- CounterListActivity
StatsActivity "1" o-- "0..*" LogModel
CounterListModel "1" o-- "0..*" CounterModel
CounterModel --o CustomAdapter
CounterListActivity "1" o-- "1" CounterListModel
CounterListActivity "1" o-- "1" CustomAdapter
CustomAdapter --|> CustomStatsAdapter
CustomStatsAdapter "1" --o "1" StatsActivity
CustomAdapter "1" o-- "1" CounterListModel
CustomAdapter "1" <|-- "1" ViewHolder
CustomStatsAdapter "1" <|-- "1" ViewHolder
AddCounterActivity --|> CounterListActivity
RenameCounterActivity --|> CounterListActivity
@enduml
