' https://github.com/hatchard/Assignment1-CMPUT301/blob/master/app/doc/hatchard_reflex_UML.jpeg
' o
@startuml
class SortStats {
  +max10: Long
  +min10: Long
  +avg10: Long
  +med10: Long
  +avg100: Long
  +max100: Long
  +min100: Long
  +med100: Long
  +avgAll: Long
  +maxAll: Long
  +minAll: Long
  +medAll: Long
  +results: ArrayList<Long>
  +sortIt(stats:ArrayList): ArrayList<Long>
  +sortAll(all:ArrayList)
  +sort100(last100:ArrayList)
  +sort10(last10:ArrayList)
  +calculateAverage(list:List)
}

class "Statistics (Activity)" {
  +sortStats: SortStats
  -FILENAME: String = reactionTimerStats
  -BUZZERFILENAME: String = buzzerStats
  +oldWinnersList: HashMap<String, ArrayList>
  +oldTimesArray: ArrayList<Long>
  +results: ArrayList<Long>
  +players2: ArrayList
  +players3: ArrayList
  +players4: ArrayList
  +getStatistics(): StringBuilder
  +composeEmail(subject:String,info:String)
  +makeStartList(context:Context)
  +saveStuff()
  +saveBuzzerStuff()
  +loadFromFile(context:Context)
  +loadFromBuzzerFile(context:Context)
  +displayBuzzerStats()
  +displayStats(results:ArrayList<Long>)
  +saveInFile(context:Context)
  +saveInBuzzerFile(context:Context)
}

class "ActivityChoice (Activity)" {
  +goToPlayerSelection(view:View)
  +goToReactionTimer(view:View)
  +goToDisplayStats(view:View)
}

class "Multiplayer (Activity)" {
  +goTo2Player(view:View)
  +goTo3Player(view:View)
  +goTo4Player(view:View)
}

class "Players2 (Activity)" {
  +showWinner(view:View)
}

class "Players3 (Activity)" {
  +showWinner(view:View)
}

class "Players4 (Activity)" {
  +showWinner(view:View)
}

class WinningPlayer {
  +popUpBox(activity:Activity,winner:String)
}

class "<<Interface>>Reaction" {
  +getTime(): Long
}

class "ReactionTimer (Activity)" {
  -time: Long
  +stat: Statistics
  +setTime(time:Long)
  +getTime(): Long
  +preReaction()
  +displayReactionTime(begin:long,timer:Timer)
  +reactionTimerPopUp(totalTime:Long)
  +resetIt()
  +complain()
}

"Statistics (Activity)" "1" o-- "*" "SortStats"
"ActivityChoice (Activity)" "1" o-- "1" "Statistics (Activity)"
"ActivityChoice (Activity)" "1" o-- "1" "Multiplayer (Activity)"
"Multiplayer (Activity)" "1" o-- "1" "Players2 (Activity)"
"Multiplayer (Activity)" "1" o-- "1" "Players3 (Activity)"
"Multiplayer (Activity)" "1" o-- "1" "Players4 (Activity)"
"Players2 (Activity)" "1" o-- "*" "WinningPlayer"
"Players3 (Activity)" "1" o-- "*" "WinningPlayer"
"Players4 (Activity)" "1" o-- "*" "WinningPlayer"
"ReactionTimer (Activity)" "1" ..|> "<<Interface>>Reaction"
@enduml