@startuml
class Student {
Name
Address
Phone Number
Email Address
Student Number
Average Mark
Is Eligible To Enroll
Get Seminars Taken
}

class Enrollment {
Marks Received
Get Average To Date
Get Final Mark
}

class Seminar {
Name
Seminar Number
Fees
Add Student
Drop Student
}

class Professor {
Name
Address
Phone Number
Email Address
Salary
}

Student "1" --> "1..*" Enrollment : enrolled
Enrollment "1.." --> "1" Seminar : in
Student "0..*{ordered, FIFO}" <-- "0..*" Seminar : on waiting list

Professor "0..1" -- "0..*" Seminar : instructs
note right of Professor
?Some seminars may not have an instructor?
end note
@enduml