@startuml
class Node<E> {
    + Node(E, Node<E>, Node<E>)
    - right: Node<E>
    - element: E
    - left: Node<E>
}

class BST {
    - root: Node<E>
    + BST()
    + root(): Node<E>
    + size(): int
    + size(Node<E>): int
    + insert(E): void
    + insert(E, Node<E>): Node<E>
    + remove(E): void
    + remove(E, Node<E>): Node<E>
    + smallestElement(): E
    + smallestElement(Node<E>): E
    + nodesByLevel(): Map<Integer, List<E>>
    + processBstByLevel(Node<E>, Map<Integer, List<E>>, int): void
    + height(): int
    + height(Node<E>): int
    + find(E, Node<E>): Node<E>
    + inOrder(): Iterable<E>
    + inOrderSubtree(Node<E>, List<E>): void
    + preOrder(): Iterable<E>
    + preOrderSubtree(Node<E>, List<E>): void
    + postOrder(): Iterable<E>
    + postOrderSubtree(Node<E>, List<E>): void
    + toString(): String
    + toStringRec(Node<E>, int, StringBuilder): void
    - empty: boolean
}

class TREE {
    + iterator(): Iterator<E>
    + autumnTree(): BST<E>
    + copyRec(Node<E>): Node<E>
    + ascdes(): Iterable<E>
    + ascSubtree(Node<E>, List<E>): void
    + desSubtree(Node<E>, List<E>): void
}

class BSTIterator {
    - stack: Stack<Node<E>>
    - curElement: E
    - canRemove: boolean
    + BSTIterator()
    + hasNext(): boolean
    + next(): E
    + remove(): void
}

class FinishedProject {
    + FinishedProject(String, String, int, int)
    + FinishedProject(ArrayList<String>)
    + equals(Object): boolean
    + toString(): String
    + compareTo(FinishedProject): int
    - completionTime: int
    - projectReference: String
    - delay: int
    - projectType: String
}

class TreeFinishedProject {
    + TreeFinishedProject()
    + TreeFinishedProject(String)
    + importData(String): void
    + equals(Object): boolean
}

class FinishedActivity {
    + FinishedActivity(String, String, String, int, int)
    + equals(Object): boolean
    + compareTo(FinishedActivity): int
    - projectReference: String
    - delay: int
    - activityType: String
    - duration: int
    - activityCode: String
}

class TreeFinishedActivity {
    + TreeFinishedActivity()
    + TreeFinishedActivity(String)
    + PrintProjectsAndActivitiesByOrderByDelayTime(): void
    + allActivitiesFromAproject(FinishedProject): List<FinishedActivity>
    + equals(Object): boolean
}

class ProjectBuild {
    + importData(String, String): void
    + lateActivitiesOfTwoProjects(FinishedProject, FinishedProject): void
    - projectTree: TreeFinishedProject
    - activityTree: TreeFinishedActivity
}

BST <|-- TREE
BST <|-- TreeFinishedProject
BST <|-- TreeFinishedActivity

Node  --0  BST
Node "1" <--* "1" BST 
Node  <..  BST : «create»

Node <--* BSTIterator

TREE  ..>  Node: «create»
TREE  0--  BSTIterator
TREE  ..>  BSTIterator : «create»

FinishedProject  <.. TreeFinishedProject : «create»
FinishedActivity <.. TreeFinishedActivity : «create»

TreeFinishedProject "1" <--* "1" ProjectBuild 
TreeFinishedActivity "1" <--* "1" ProjectBuild 
TreeFinishedProject  <..  ProjectBuild : «create»
TreeFinishedActivity  <..  ProjectBuild : «create»

@enduml