' https://github.com/manishnasa/TrafficProblem/blob/master/ClassDiagram.png
' o
@startuml

' Define packages
package "Common.Graph" {
    interface IEdge
    interface IVertex
    interface IShortestPathAlgorithm
    class Edge
    class Vertex
    class Dijkstra
}

package "Common.Logger" {
    interface ILogger
    class DumbConsoleLogger
}

package "TrafficSystemContract" {
    interface IStreet
    interface ISignal
    interface ITrafficControlRoom
    interface IRoute
}

package "TrafficSystem" {
    class Street
    class Signal
    class SpecialDijkstra
    class TrafficControlRoom
    class Route
}

' Implementations (Realization)
Edge ..|> IEdge
Vertex ..|> IVertex
Dijkstra ..|> IShortestPathAlgorithm
DumbConsoleLogger ..|> ILogger
Street ..|> IStreet
Signal ..|> ISignal
TrafficControlRoom ..|> ITrafficControlRoom
Route ..|> IRoute

' Inheritance
SpecialDijkstra --|> Dijkstra
Street --|> Edge
Signal --|> Vertex

' Notes
note bottom of SpecialDijkstra
Singleton
end note

note bottom of DumbConsoleLogger
Singleton
end note

IStreet --> IEdge
ISignal --> IVertex

@enduml