@startuml
'https://github.com/lopossumi/brkut/blob/master/images/ClassDiagramW1.png
'o
class Main {
}

class Game {
}

class FileReader {
  {field} configFile
}

class KeyListener {
}

class Logic {
  {field} Level
  {field} Lives
  {field} Score
}

class GUI {
}

class JFrame {
}

class GameObject {
  {field} boundingBox
}

class Ball {
}

class Paddle {
}

class Brick {
}

class Wall {
}

Main --> Game : Game
Main --> FileReader : FileReader
Game --> KeyListener : KeyListener
Game --> Logic : Logic
Game --> GUI : GUI
Logic --> GameObject : GameObject
GUI --> JFrame : JFrame
GameObject <|-- Ball
GameObject <|-- Paddle
GameObject <|-- Brick
GameObject <|-- Wall
@enduml