'https://github.com/tmrcs/images/blob/master/UML/CommandExecuter.png
's
@startuml
class Listen {
  -server : Server
  +Listen(CommandExecutor)
  +execute(HashMap<String, String>) : ArrayList<String>
  +getCommandExecutor() : CommandExecutor
  +stopServer() : void
}

class Command {
  -description : String
  -handler : DataHandler
  +Command(FormatParser, DataHandler, String, String)
  +execute(HashMap<String, String>) : ArrayList<String>
  +toString() : String
  +shutdown() : boolean
  +getFormatter(String, String) : Formatter
}

class CommandExecutor {
  +CommandExecutor(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +executeCommand(String, HashMap<String, String>) : ArrayList<String>
  +getCommandParser() : CommandParser
  +getCurrentCommand() : Command
}

class FormatParser {
  +FormatParser(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +addFormatters(UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler) : void
  +get(String, String) : Formatter
}

class CommandParser {
  +CommandParser(CommandExecutor, FormatParser, UserHandler, PromotionHandler, PurchaseHandler, CategoryHandler)
  +CommandParser()
  +addCommands(CommandExecutor, FormatParser, UserHandler, PromotionHandler, PurchaseHandler) : void
  +get(String, HashMap<String, String>) : Command
}

Command <|-- Listen
Listen " " --> "0..1" CommandExecutor : -executor
CommandExecutor " " --> "0..1" Command : -currentCommand
CommandExecutor " " --> "0..1" CommandParser : -commandParser
CommandExecutor " " --> "0..1" FormatParser : -formatterParser
Command " " --> "0..1" FormatParser : #formatters

@enduml