'https://github.com/edcu11/examen1progra3/blob/master/DiagramParte2.png
'o
@startuml
class Operador {
  +numero1 : int
  +numero2 : int
  +Operador()
  +getTipo() : string
  +operar() : int
  +operator==(operador:Operador*) : bool
}

class Sumar {
  +Sumar(numero1:int, numero2:int)
  +operar() : int
  +getTipo() : string
}

class Restar {
  +Restar(numero1:int, numero2:int)
  +operar() : int
  +getTipo() : string
}

Operador <|-- Sumar
Operador <|-- Restar

@enduml