'https://github.com/alihitawala/DesignPatterns/blob/master/src/main/java/com/learning/patterns/structural/adapter/UML-Adapter.png
'o
@startuml
class LegacyLine {
}

class Shape {
}

class LegacyRectangle {
}

class Line {
}

class Rectangle {
}

LegacyLine <|-- Line
Shape <|-- Line
Shape <|-- Rectangle

Line "1" --> "1" LegacyLine
Rectangle "1" --> "1" LegacyRectangle

Line ..> LegacyLine : <<create>>
Rectangle ..> LegacyRectangle : <<create>>

@enduml