
'https://github.com/ProjetJavaJeu/Projet/blob/master/Rapport/Document%202/UML3.png
@startuml
package "GUI" {
  class TriggerControle {
    -NomMembre
    -NomMembre
  }

  class FenetreJeu {
    -NomMembre
    -NomMembre
  }

  class Controller {
    -NomMembre
    -NomMembre
  }

  class Joueur {
    -NomMembre
    -NomMembre
  }

  class Camera {
    -NomMembre
    -NomMembre
  }

  class Carte {
    -NomMembre
    -NomMembre
  }
}

package "PPersonnages" {
  class Caract {
    -int Force
    -int Intelligence
    -int Endurance
    -int CaractSecondaire[] //A mettre dans une DB en ligne
    +Accesseurs
  }

  class Personnages {
    -String nom
    -Caract caracteristiques
    -int pv
    -int type //
    -NomMembre
  }

  class MonstresCommuns {
    -int xpDonnee
    -int coordX
    -int coordY
    -String replique
    +xpDonnee(?)
  }

  class MonstresElites {
    -int xpDonnee
    -int coordX
    -int coordY
    -String replique
    +xpDonnee(?)
  }

  class Mage {
    -int mana
    -int niveau
  }

  class Guerrier {
    -int niveau
  }

  class XpMonstres {
    -int xpDonnee
  }

  class XpPerso {
    -int xpAct
    -int xp[] //A mettre dans une DB en ligne
    +checkXP(int xpAct, int level)
    +setLevel(int xpAct, int xpMoins, int level)
  }
}

class Main {
  -NomMembre
  -NomMembre
}

class VerifCombat {
  -NomMembre
  -verifCase()
}

class Combat {
  -NomMembre
  -NomMembre
}

' Relationships within GUI package
FenetreJeu  o--  TriggerControle
FenetreJeu  o--  Controller
FenetreJeu  o--  Joueur
FenetreJeu  o--  Camera
FenetreJeu  o--  Carte

' Relationships within PPersonnages package
Caract  --o  Personnages 
Personnages <|-- MonstresCommuns
Personnages <|-- MonstresElites
Personnages <|-- Mage
Personnages <|-- Guerrier


XpMonstres --o  MonstresCommuns 
XpMonstres  --o  MonstresElites

XpPerso  --o  Mage 
XpPerso  --o  Guerrier 

' Relationships between packages and other classes

@enduml
