'https://github.com/itgkarl/SeleniPo/blob/master/Files/VisualPara/strukturTestharness.jpg
@startuml
class ByFactory {
  +link(locator: String): By
  +xpath(locator: String): By
  +href(locator: String): By
  +checkbox(locator: String): By
  +radioButton(locator: String): By
  +input(locator: String): By
  +button(locator: String): By
  +id(locator: String): By
  +textArea(locator: String): By
  +textField(locator: String): By
  +select(locator: String): By
}

class PageObject {
  #driver: WebDriver
  +getDriver(): WebDriver
  +getBy(): ByFactory
  #control(bys: By...): Control
}

class BasePo {
  +BasePo()
  +BasePo(po: PageObject)
}

class PageObject_Generated {
}

class PageObject_Dynamisch {
}

interface Control {
  +resolve(): WebElement
  +sendKeys(text: String)
  +uncheck()
  +check()
  +click()
  +setText(text: String)
  +setText(text: Object)
  +select(option: String)
  +value(): String
  +isReadonly(): boolean
}

class ControlBys {
  -parent: PageObject
  -bys: By[]
  +ControlBys(parent: PageObject, bys: By...)
  #find(selector By): WebElement
}

ByFactory "1" -- "0" PageObject
PageObject <|-- BasePo
BasePo <|-- PageObject_Generated
PageObject_Generated <|-- PageObject_Dynamisch
PageObject_Generated "0" -- "0..*" Control
ControlBys ..|> Control
@enduml
