' https://github.com/kukuruza/cmu-bus/blob/master/client/classDiagrams/Database_UML_diagram.png
' o
@startuml
class Schedule {
  +Schedule_id :
  +Route_id :
  +Weekday :
  +Time :
}

class Stops {
  +Stop_id :
  +Street2 :
  +Name :
  +GPS_Latitude :
  +Street1 :
  +GPS_Longitude :
}

class Route {
  +Route_id :
  +Bus_id :
  +Stop_id :
}

class Bus {
  +Bus_id :
  +Name :
  +Direction :
}

Route  "0..n" --  Schedule
Route  -- "0..n" Stops
Route  -- "0..n" Bus
@enduml