' https://github.com/kukuruza/cmu-bus/blob/master/client/classDiagrams/timeQuery.png
' s
@startuml
class GlobalManager <<cmu18641.bustracker.ws>> {
  + routeQueryManager: RouteQueryManager
  + locationService: LocationService
  + GlobalManager()
  + getBusesByStop()
  + getStopsByCurrentLocation()
  + getStopByAddress()
  + killLocationService()
  + getSchedule()
  + updateDatabase()
}

class TimeQueryManager <<cmu18641.bustracker.ws>> {
  numOut: int
  TimeQueryManager()
  getSchedule()
}

class LocalQuery <<cmu18641.bustracker.ws.local>> {
  LocalQuery()
  getSchedule()
}

class RemoteQuery <<cmu18641.bustracker.ws.remote>> {
  RemoteQuery()
  getSchedule()
}

class TimeQueryInterface <<cmu18641.bustracker.ws>> {
  getSchedule()
}

class Networking <<cmu18641.bustracker.ws.remote>> {
  Networking()
  isNetworkAvailable()
  askServer()
  requestFile()
}

GlobalManager "1" --> "0..1" TimeQueryManager : ~timeQueryManager
LocalQuery ..|> TimeQueryInterface
RemoteQuery ..|> TimeQueryInterface
TimeQueryManager ..> Networking
RemoteQuery ..> Networking
GlobalManager ..> Networking
TimeQueryManager ..> RemoteQuery
TimeQueryManager ..> LocalQuery
@enduml