' https://github.com/koko67/BattleshipTeam4/blob/master/model/diagram-class.png
' o
@startuml
class Game {
  +name: string
  +players: Array
  +shots: Number
  +startGame(): void
  +finishGame(): Player
}

class Table {
  +size: Number
  +ships: Array(Ship)
  +sortShips(): void
}

class Ship {
  +size: Number
  +alignment: Number
}

class Shot {
  +posX: Number
  +posY: Number
}

class Player {
  +name: String
  +shot: Shoot
  +shoot(Number x, Number y): bool
}

class Main {
  +game: Game
  +createGame(): void
}

Game --> Table
Table --> Ship
Game --> Player
Player --> Shot
Main --> Game
@enduml