' https://github.com/nicolaschriste/nicolaschriste.github.io/blob/master/docdown/reference/markdown/img/uml.png
' o
@startuml

class Provider
class DataProvider
class Entry

DataProvider -|> Provider
DataProvider "1" -- "*" Entry

@enduml