' https://github.com/Java-Archive/Modules/blob/develop/data/blog-20131016/full-uml.png
' s
@startuml

class DemoContext {
  + toggle : boolean
  + getContextInfo() : boolean
}

interface CDICallable

class LeftTextFieldBindingCallable {
  + demoLogic : Instance<DemoLogic>
  + call() : String
}

class RightTextFieldBindingCallable {
  + demoLogic : Instance<DemoLogic>
  + call() : String
}

class PairedTextField {
  + leftTextField : TextField
  + rightTextField : TextField
  + hb : HBox
  + spacing : int
  + leftTextFieldBindingCallableInstance : Instance<LeftTextFieldBindingCallable>
  + rightTextFieldBindingCallableInstance : Instance<RightTextFieldBindingCallable>
  + demoContext : DemoContext
  + init() : void
  + setAnchors(node, Double) : void
}

interface DemoLogic {
  + doIt() : String
}

class KotlinDemoLogic {
  + doIt() : String
}

class DemoLogicB {
  + doIt() : String
}

class KotlinDemoLogicProducer {
  + create(kotlinDemoLogic : KotlinDemoLogic) : DemoLogic
}

class DemoLogicProducerB {
  + create(beanManager, injectionPoint, demoLogicB : DemoLogicB) : DemoLogic
}

class DemoLogicProducer {
  + creator : ManagedInstanceCreator
  + create(resolver : DemoContextResolver) : DemoLogic
}

class DemoContextResolver {
  + demoContext : DemoContext
  + resolveContext(Class<?>) : ActionLiteral
}

class KotlinDemoLogicContext
class DemoLogicContextB

CDICallable <|-- LeftTextFieldBindingCallable
CDICallable <|-- RightTextFieldBindingCallable

PairedTextField "1" *-- "*" LeftTextFieldBindingCallable : leftBindings
PairedTextField "1" *-- "*" RightTextFieldBindingCallable : rightBindings

LeftTextFieldBindingCallable --> DemoLogic : uses
RightTextFieldBindingCallable --> DemoLogic : uses

KotlinDemoLogic ..|> DemoLogic
DemoLogicB ..|> DemoLogic

KotlinDemoLogicProducer ..> KotlinDemoLogic
KotlinDemoLogicProducer ..> DemoLogic

DemoLogicProducerB ..> DemoLogicB
DemoLogicProducerB ..> DemoLogic

DemoLogicProducer ..> DemoContextResolver
DemoLogicProducer ..> DemoLogic

DemoContextResolver ..> KotlinDemoLogicContext
DemoContextResolver ..> DemoLogicContextB

PairedTextField "1" *--> "1" DemoContext
DemoContext "1" <--* "1" DemoContextResolver

@enduml