@startuml
'https://github.com/lopossumi/brkut/blob/master/documentation/Class%20diagrams/ClassDiagram-2014-12-03.png
'o
package "Main" {
    class HighscoreIO {
    }

    class Config {
        newOperation()
    }

    class Main {
    }

    HighscoreIO -- Main
    Config -- Main
}

package Engine {
    class Panel {
    logic : Logic
    tick : int
    }

    class JPanel {
    }

    class SoundEngine {
    hit()
    died()
    }

    class Engine {
    gui : GUI
    logic : Logic
    running : boolean
    sounds : SoundEngine
    }

    class GUI {
    window : JFrame
    logic : Logic
    input : UserInput
    panel : Panel
    }

    class UserInput {
    keyPresses : boolean
    }

    enum KeyPressEnum {
    LEFT : int
    RIGHT : int
    SPACE : int
    }

    Engine *--> SoundEngine
    Engine *--> GUI
    GUI *--> UserInput
    UserInput -- KeyPressEnum
    GUI *--> Panel
    Panel --|> JPanel

}

package Logic {

    enum GameStatusEnum {
    START : int
    RUNNING : int
    WON : int
    DIED : int
    GAMEOVER : int
    HIT : int
    HIGHSCORE : int
    }

    class Collision {
    getColliders()
    collision()
    clear()
    xOverlap()
    yOverlap()
    }

    class Logic {
    playerOne : Player
    ball : Ball
    bricks : HashSet<GameObject>
    score : int
    multiplier : double
    highscore : int
    hit : boolean
    launchAllowed : boolean
    }

    class GameObject {
    x : double
    y : double
    vx : double
    vy : double
    width : double
    height : double
    maxSpeed : double
    color : Color
    }

    class Player {
    alive : boolean
    lives : int
    kill()
    respawn()
    }

    class Ball {
    bounceHorizontal()
    bounceVertical()
    }

    class Brick {
    alive : boolean
    hitpoints : int
    damage()
    }

    Logic *--> GameObject

    Logic -- GameStatusEnum
    Logic -- Collision

    GameObject <|-- Player
    GameObject <|-- Ball
    GameObject <|-- Brick

}

Engine *--> Logic
Logic *--> GUI
Engine <-- Main



@enduml