@startuml
class User {
+FirstName [1..1] : String
+LastName [1..1] : String
+DateOfBirth [1..1] : Date
+<<PK>>Username [1..1] : String
+Password [1..1] : String
+Phone [0..*] : int
}

class ActivityTracker {
+CreatedOn [1..1] : Date
+ModifiedOn : Date
}

class UserActivity {
+Name [1..1] : String
}

class Note {
+Text : blob
+Image [0..*] : blob
}

class Event {
+Venue : String
+StartDate : Date
+EndDate : Date
+Occurrence : Occurrence
}

class Appointment {
+DateOfAppointment : Date
+Purpose : String
+Location : String
+Duration : int
+Priority : Priority
}

enum Priority {
Low
Medium
High
}

enum Occurrence {
Daily
Weekly
Monthly
Annually
}

User "1" -- "0..*" UserActivity : +createdBy
ActivityTracker "1" .. "0.." UserActivity : +creates
UserActivity <|-- Note : +{disjoint}
UserActivity <|-- Event : +{disjoint}
UserActivity <|-- Appointment : +{disjoint}
@enduml